name: codex
description: Codex

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-166.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.0.0+2
  flutter_bloc: ^7.2.0
  flutter_svg: ^0.22.0
  fast_barcode_scanner: ^1.1.0
  shared_preferences: ^2.0.7
  rainbow_color: ^2.0.1
  store_redirect: ^2.0.0
  package_info: ^2.0.2
  connectivity: ^3.0.6
  version: ^2.0.0
  tcard: ^1.3.5
  http: ^0.13.3
  google_mobile_ads: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

  assets:
    - assets/images/tv.png
